sudo: required
services:
  - docker

before_install:
  - docker build -t caldito99/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run caldito99/react-test npm test -- --coverage

after_success:
  - docker build -t caldito99/multi-client ./client
  - docker build -t caldito99/multi-nginx ./nginx
  - docker build -t caldito99/multi-server ./server
  - docker build -t caldito99/multi-worker ./worker
  #login dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin   
  #Push to dockerhub
  - docker push caldito99/multi-client
  - docker push caldito99/multi-nginx
  - docker push caldito99/multi-server
  - docker push caldito99/multi-worker
deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-161067368138
  bucker_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
